// src/components/cards/QuoteCard.tsx
import Card from './Card';

interface QuoteCardProps {
  quote: string,
  author: string,
}

export default function QuoteCard({quote, author}: QuoteCardProps) {
  return (
    <Card styles='w-[75vw] md:w-[38vw] mx-auto text-xl pt-6 leading-6'>
      <>
        <blockquote className='mt-3'>
          {quote}
        </blockquote>

        <div className='mt-4 w-full text-end'>
          <cite>
            <small className='text-sm'>
              {author}
            </small>
          </cite>
        </div>
      </>
    </Card>
  );
}

// src/lib/QuoteCard.svelte
<script lang="ts">
  import Card from './templates/Card.svelte'

  export let quote: string
  export let author: string
</script>

<Card
  _class={'w-[75vw] md:w-[40vw] mx-auto mt-[3.5em] text-xl pt-8 leading-7'}
>
  <blockquote class="mt-3">
    {quote}
  </blockquote>

  <div class="mt-6 w-full text-end">
    <cite>
      <small class="text-md">
        {author}
      </small>
    </cite>
  </div>
</Card>
